# Generated by Django 6.1 on 2026-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
